<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE root [
<!ELEMENT root (elem1,elem2,elem3,elem3,elem4)>
<!ELEMENT elem1 (#PCDATA)>
<!ELEMENT elem2 EMPTY>
<!ELEMENT elem3 ANY>
<!ELEMENT elem4 (otro*)>
<!ELEMENT otro (algomas+)>
<!ELEMENT algomas EMPTY>
<!ATTLIST elem1 version CDATA "1.12358">
<!ATTLIST elem3 att1 CDATA #REQUIRED>
<!ATTLIST elem3 att2 CDATA #FIXED "algo2">
<!ATTLIST elem3 att3 CDATA #IMPLIED>
<!ATTLIST otro att CDATA #IMPLIED>
]>

<!--
    Document   : newXMLDocument.xml
    Created on : 21 de octubre de 2007, 15:07
    Author     : Mateo
    Description:
        Purpose of the document follows.
-->
<root>
    <elem1>Elemento1</elem1>
    <elem2/>
    <elem3 att1="algo1" att2="algo2">
	HH
	<![CDATA[Algo para destacar]]>
    </elem3>
    <elem3 att1="algo1" att2="algo2" att3="huevada"/>
    <elem4>
        <otro>
            <algomas/>
            <algomas/>
        </otro>
        <otro att="asd">
            <algomas/>
        </otro>
    </elem4>
</root>